language: python
python:
  - "2.7"

branches:
  only:
    - master
    - feature-review

install:
  - pip install -r requirements.txt
  - pip install coveralls

env:
  - DB=sqlite

script:
  - python bucketlist/manage.py test bucketlist/api/ --noinput --settings=bucketlist.test_settings

after_success:
  - coveralls
